spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:1991/user-db
    username: postgres
    password: 1991
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

server:
  port: 8081

keycloak:
  realm: cydeo-dev
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: ticketing-app
  credentials:
    secret: 0b4fLhHffgZUTmLJLfNi9w9BwJDAR8pv
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: admin
    password: admin
  realm: master
  client: master-client

eureka:
  instance:
    preferIpAddress: true
    ipAddress: 127.0.0.1
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator

info:
  application:
    name: user-service
    description: Ticketing Application User Service